source 'https://rubygems.org'

# gem 'gosu'
gem 'rspec'
gem 'simplecov'
gem 'rubocop'
gem 'metric_fu'
gem 'cucumber'
gem 'guard'
gem 'guard-cucumber'
gem 'guard-rspec', require: false
gem 'guard-cane', '>= 0.2.1'
gem 'guard-rubocop'
gem 'guard-bundler'
gem 'activesupport'
